sudo: required
services:
  - docker

before_install:
  - docker build -t sakipgur/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sakipgur/docker-react:latest npm test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-112569602180"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
