sudo: required
services:
  - docker

before_install:
  - docker build -t sakipgur/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sakipgur/docker-react:latest npm run test -- --coverage
